include::requirement_properties.adoc[]

== Responsible
*{requirement_responsible}*
is the contact person for this requirement.
The contact person accompanies this requirement over the entire life cycle.

== Identifier

{requirement_id} : {requirement_name}

== Description

=== What should be improved/solved with the requirement?
* Analyze an ecg including all available ecg channels
** Support for multiple <<Supported Devices, ECG devices>>
** Detect and annotate episodes of Atrial Fibrillation (AF) and Atrial Flutter (AFl) of 30s and more
** Detect and annotate signal noise and artefacts in each channel
** Calculate the atrial fibrillation burden (AF Burden) in terms of
*** the longest episode of AF/AFl measured in seconds
*** the percentage of AF/AFl, e.g., 14% for a total of 42s of af in a 300s recording
** Calculate the Heart Rate Variability (HRV) using root mean square of successive differences (RMSSD) in milliseconds
** Calculate the signal quality in terms of net time without artefacts or signal noise
** Calculate the heart rate (exclude noisy areas to avoid measurement errors)
** Analysis result is uniquely identifiable (without referencing the specific patient)

=== Value
* Analysis result include following information:
** AF was correctly detected and annotated
** Noise was correctly detected and annotated
** Calculated AF burden
** Calculated HRV
** Calculated signal quality
** Calculated heart rate

* Authorized user can access the correct result
* Authorized user generally do not need more than 20 seconds to access the result

* The user needs maximum 3 seconds to classify the result.
* A printable document format is available.

* Notes for proposal:
** The Analysis will have a medical purpose. This makes the following steps necessary:
*** More details will be part of the validation plan and clinical evaluation
*** Precise definition is therefore made in the corresponding process activities

=== Supported Devices
* Bittium Faros